#!/usr/bin/env python3
"""
resume_clean.py — Strip AI-tool metadata from .docx resumes and flag
statistical / stylistic "AI-generated" signals in the text (the kind of
signal ATS plugins and AI-detector heuristics actually key on).

There is no watermark to remove from resume text (no hidden token-sampling
signal). What actually gets flagged is:
  1. Document metadata ("Generated by ChatGPT", app name, etc.)
  2. AI-cliche phrasing (stock LLM-isms)
  3. Low "burstiness" — unnaturally uniform sentence length / structure
  4. Repetitive bullet openers (every bullet starting the same way)

Usage:
    python3 resume_clean.py inspect resume.docx
    python3 resume_clean.py clean   resume.docx -o resume.cleaned.docx
    python3 resume_clean.py inspect resume.txt
"""
import argparse
import io
import re
import statistics
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

# ---------------------------------------------------------------------------
# 1. DOCX METADATA
# ---------------------------------------------------------------------------

CORE_NS = "http://schemas.openxmlcalendar/does-not-matter"  # placeholder, unused
DOCPROPS_CORE = "docProps/core.xml"
DOCPROPS_APP = "docProps/app.xml"
CUSTOM_XML_PREFIX = "customXml/"

# Namespaces used in docProps/core.xml
NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
}

# app/tool names that leak "this was AI-generated / AI-assisted" info
SUSPICIOUS_TOKENS = [
    "chatgpt", "openai", "gpt-", "gpt4", "gpt-4", "claude", "anthropic",
    "gemini", "bard", "copilot", "jasper", "rytr", "writesonic",
    "resumeworded", "kickresume ai", "teal ai", "rezi ai", "novoresume ai",
    "ai-generated", "generated by ai", "chat gpt",
]


def inspect_docx_metadata(path: Path) -> dict:
    report = {"core_props": {}, "app_props": {}, "suspicious_hits": [], "custom_xml_files": []}
    with zipfile.ZipFile(path) as z:
        names = z.namelist()

        if DOCPROPS_CORE in names:
            core_xml = z.read(DOCPROPS_CORE)
            root = ET.fromstring(core_xml)
            for child in root:
                tag = child.tag.split("}")[-1]
                report["core_props"][tag] = child.text or ""

        if DOCPROPS_APP in names:
            app_xml = z.read(DOCPROPS_APP)
            root = ET.fromstring(app_xml)
            for child in root:
                tag = child.tag.split("}")[-1]
                report["app_props"][tag] = child.text or ""

        report["custom_xml_files"] = [n for n in names if n.startswith(CUSTOM_XML_PREFIX)]

        all_text_blobs = list(report["core_props"].values()) + list(report["app_props"].values())
        for n in report["custom_xml_files"]:
            try:
                all_text_blobs.append(z.read(n).decode("utf-8", errors="ignore"))
            except Exception:
                pass

        haystack = " ".join(all_text_blobs).lower()
        for token in SUSPICIOUS_TOKENS:
            if token in haystack:
                report["suspicious_hits"].append(token)

    return report


def clean_docx_metadata(path: Path, out_path: Path) -> dict:
    """Blank out core/app properties that commonly carry tool/author fingerprints
    and strip customXml parts (often used by AI writing tools to tag output)."""
    removed = {"core_props_cleared": [], "app_props_cleared": [], "custom_xml_removed": []}

    with zipfile.ZipFile(path) as zin:
        names = zin.namelist()
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)

                if item.filename == DOCPROPS_CORE:
                    root = ET.fromstring(data)
                    for child in list(root):
                        tag = child.tag.split("}")[-1]
                        # Keep title/language if meaningful; blank fingerprint-y fields
                        if tag in ("creator", "lastModifiedBy", "description", "keywords", "subject", "category"):
                            if child.text:
                                removed["core_props_cleared"].append(f"{tag}={child.text!r}")
                            child.text = ""
                    data = ET.tostring(root, encoding="utf-8", xml_declaration=True)

                elif item.filename == DOCPROPS_APP:
                    root = ET.fromstring(data)
                    for child in list(root):
                        tag = child.tag.split("}")[-1]
                        if tag in ("Application", "AppVersion", "Company", "Manager"):
                            if child.text:
                                removed["app_props_cleared"].append(f"{tag}={child.text!r}")
                            child.text = ""
                    data = ET.tostring(root, encoding="utf-8", xml_declaration=True)

                elif item.filename.startswith(CUSTOM_XML_PREFIX):
                    removed["custom_xml_removed"].append(item.filename)
                    continue  # drop entirely

                zout.writestr(item, data)

        out_path.write_bytes(buf.getvalue())

    return removed


# ---------------------------------------------------------------------------
# 2. TEXT EXTRACTION (docx -> plain bullets, or plain text file)
# ---------------------------------------------------------------------------

def extract_text_from_docx(path: Path) -> list[str]:
    lines = []
    with zipfile.ZipFile(path) as z:
        xml = z.read("word/document.xml")
    root = ET.fromstring(xml)
    w_ns = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
    for p in root.iter(f"{w_ns}p"):
        texts = [t.text or "" for t in p.iter(f"{w_ns}t")]
        line = "".join(texts).strip()
        if line:
            lines.append(line)
    return lines


def extract_text_from_plain(path: Path) -> list[str]:
    return [l.strip() for l in path.read_text(encoding="utf-8", errors="ignore").splitlines() if l.strip()]


# ---------------------------------------------------------------------------
# 3. AI-CLICHE / STYLE HEURISTICS
# ---------------------------------------------------------------------------

CLICHE_PHRASES = [
    "leverage", "leveraging", "synerg", "spearhead", "spearheaded",
    "cutting-edge", "cutting edge", "seamless", "seamlessly", "robust",
    "dynamic environment", "fast-paced environment", "in today's",
    "furthermore", "moreover", "utilize", "utilizing", "delve into",
    "delve", "holistic", "streamline", "streamlined", "revolutioniz",
    "game-chang", "game changer", "unparalleled", "best-in-class",
    "state-of-the-art", "paradigm shift", "at the intersection of",
    "underscore", "underscores", "underscoring", "bespoke", "elevate",
    "elevating", "meticulous", "meticulously", "proven track record",
    "results-driven", "results-oriented", "passionate about",
    "extensive experience", "wide range of", "vast array",
    "plethora", "tapestry", "navigat", "harness the power",
    "unlock the potential", "drive impactful", "drive meaningful",
    "foster", "fostering", "empower", "empowering", "align with",
    "in conclusion", "it is important to note", "it's worth noting",
]

# ---------------------------------------------------------------------------
# 3b. HARVARD FAS "CREATE A STRONG RESUME" RULES
#     https://careerservices.fas.harvard.edu/resources/create-a-strong-resume/
#     Quick Tips -> Action Verbs table, and the DO / DON'T lists.
# ---------------------------------------------------------------------------

# The full Harvard action-verb bank, flattened to lowercase, across all
# their categories (Leadership, Communication, Research, Technical,
# Teaching, Quantitative, Creative, Helping, Organizational).
HARVARD_ACTION_VERBS = {
    v.lower() for v in [
        # Leadership
        "Accomplished", "Achieved", "Administered", "Analyzed", "Assigned",
        "Attained", "Chaired", "Consolidated", "Contracted", "Coordinated",
        "Delegated", "Developed", "Directed", "Earned", "Evaluated",
        "Executed", "Handled", "Headed", "Impacted", "Improved",
        "Increased", "Led", "Mastered", "Orchestrated", "Organized",
        "Oversaw", "Planned", "Predicted", "Prioritized", "Produced",
        "Proved", "Recommended", "Regulated", "Reorganized", "Reviewed",
        "Scheduled", "Spearheaded", "Strengthened", "Supervised", "Surpassed",
        # Communication
        "Addressed", "Arbitrated", "Arranged", "Authored", "Collaborated",
        "Convinced", "Corresponded", "Delivered", "Documented", "Drafted",
        "Edited", "Energized", "Enlisted", "Formulated", "Influenced",
        "Interpreted", "Lectured", "Liaised", "Mediated", "Moderated",
        "Negotiated", "Persuaded", "Presented", "Promoted", "Publicized",
        "Reconciled", "Recruited", "Reported", "Rewrote", "Spoke",
        "Suggested", "Synthesized", "Translated", "Verbalized", "Wrote",
        # Research
        "Clarified", "Collected", "Concluded", "Conducted", "Constructed",
        "Critiqued", "Derived", "Determined", "Diagnosed", "Discovered",
        "Examined", "Extracted", "Formed", "Identified", "Inspected",
        "Interviewed", "Investigated", "Modeled", "Resolved", "Summarized",
        "Surveyed", "Systematized", "Tested",
        # Technical
        "Assembled", "Built", "Calculated", "Computed", "Designed",
        "Devised", "Engineered", "Fabricated", "Installed", "Maintained",
        "Operated", "Optimized", "Overhauled", "Programmed", "Remodeled",
        "Repaired", "Solved", "Standardized", "Streamlined", "Upgraded",
        # Teaching
        "Adapted", "Advised", "Coached", "Communicated", "Demystified",
        "Enabled", "Encouraged", "Explained", "Facilitated", "Guided",
        "Informed", "Instructed", "Stimulated", "Studied", "Taught", "Trained",
        # Quantitative
        "Allocated", "Appraised", "Audited", "Balanced", "Budgeted",
        "Forecasted", "Managed", "Marketed", "Maximized", "Minimized",
        "Projected", "Researched",
        # Creative
        "Acted", "Composed", "Conceived", "Conceptualized", "Created",
        "Customized", "Established", "Fashioned", "Founded", "Illustrated",
        "Initiated", "Instituted", "Integrated", "Introduced", "Invented",
        "Originated", "Performed", "Published", "Redesigned", "Revised",
        "Revitalized", "Shaped", "Visualized",
        # Helping
        "Assessed", "Assisted", "Counseled", "Demonstrated", "Educated",
        "Enhanced", "Expedited", "Familiarized", "Motivated", "Participated",
        "Proposed", "Provided", "Referred", "Rehabilitated", "Represented",
        "Served", "Supported",
        # Organizational
        "Approved", "Accelerated", "Added", "Broadened", "Cataloged",
        "Centralized", "Changed", "Classified", "Compiled", "Completed",
        "Controlled", "Defined", "Dispatched", "Expanded", "Gained",
        "Gathered", "Generated", "Implemented", "Launched", "Monitored",
        "Prepared", "Processed", "Purchased", "Recorded", "Reduced",
        "Reinforced", "Retrieved", "Screened", "Selected", "Simplified",
        "Sold", "Specified", "Steered", "Structured", "Tabulated",
        "Unified", "Updated", "Utilized", "Validated", "Verified",
    ]
}

# Harvard's explicit DON'T list: no personal pronouns (I, We, and their forms)
PRONOUN_RE = re.compile(r"\b(I|I'm|I've|I'll|I'd|We|We're|We've|My|Our|Us|Myself|Ourselves)\b")

BULLET_START_RE = re.compile(r"^(\**\s*)([A-Z][a-zA-Z]*)")


def sentence_lengths(lines: list[str]) -> list[int]:
    lengths = []
    for line in lines:
        # crude sentence split
        sentences = re.split(r"(?<=[.!?])\s+", line)
        for s in sentences:
            words = s.split()
            if words:
                lengths.append(len(words))
    return lengths


def find_cliches(lines: list[str]) -> dict:
    hits = {}
    for line in lines:
        low = line.lower()
        for phrase in CLICHE_PHRASES:
            if phrase in low:
                hits.setdefault(phrase, []).append(line[:90])
    return hits


def bullet_opener_repetition(lines: list[str]) -> dict:
    openers = {}
    for line in lines:
        content = _content_for_check(line)
        cleaned = re.sub(r"^[\*\-\u2022\s]+", "", content)
        m = BULLET_START_RE.match(cleaned)
        if m:
            word = m.group(2)
            openers[word] = openers.get(word, 0) + 1
    # only report openers used 3+ times
    return {k: v for k, v in openers.items() if v >= 3}


def _content_for_check(line: str) -> str:
    """Bullets in this resume style are written as 'Bold Label: sentence'.
    For pronoun/verb checks we want the sentence, not the label — checking
    the label ('Data Engineering & Lakehouse:', 'Data Analyst | ...') would
    misfire on job titles and skill-category names that aren't sentences."""
    if ": " in line:
        return line.split(": ", 1)[1]
    return line


def harvard_pronoun_check(lines: list[str]) -> list[str]:
    hits = []
    for line in lines:
        content = _content_for_check(line)
        if PRONOUN_RE.search(content):
            hits.append(line[:100])
    return hits


def harvard_weak_opener_check(lines: list[str]) -> list[str]:
    """Flag bullets whose opening word isn't on Harvard's action-verb list.
    Only applied to lines that look like a 'Label: sentence' bullet, since
    job titles, company names, and section headers aren't meant to open
    with an action verb in the first place."""
    flagged = []
    for line in lines:
        if ": " not in line:
            continue  # not a bullet in this format — skip (title/header/label)
        content = line.split(": ", 1)[1]
        m = re.match(r"^([A-Za-z][a-zA-Z]*)", content)
        if not m:
            continue
        first_word = m.group(1).lower()
        if first_word not in HARVARD_ACTION_VERBS:
            flagged.append(f"'{m.group(1)}' -> \"{line[:90]}\"")
    return flagged


def burstiness_report(lines: list[str]) -> dict:
    lengths = sentence_lengths(lines)
    if len(lengths) < 3:
        return {"note": "not enough sentences to score", "n": len(lengths)}
    mean = statistics.mean(lengths)
    stdev = statistics.pstdev(lengths)
    cv = (stdev / mean) if mean else 0  # coefficient of variation
    # Human writing tends to have higher variance (cv often > 0.4-0.5).
    # Very uniform AI output often sits lower.
    flag = cv < 0.35
    return {
        "sentence_count": len(lengths),
        "mean_words_per_sentence": round(mean, 1),
        "stdev": round(stdev, 1),
        "coefficient_of_variation": round(cv, 2),
        "low_variance_flag": flag,
    }


# ---------------------------------------------------------------------------
# 4. CLI
# ---------------------------------------------------------------------------

def cmd_inspect(args):
    path = Path(args.file)
    print(f"Inspecting: {path.name}\n")

    if path.suffix.lower() == ".docx":
        meta = inspect_docx_metadata(path)
        print("== DOCX metadata ==")
        for k, v in meta["core_props"].items():
            if v:
                print(f"  core.{k}: {v}")
        for k, v in meta["app_props"].items():
            if v:
                print(f"  app.{k}: {v}")
        if meta["custom_xml_files"]:
            print(f"  customXml parts present: {len(meta['custom_xml_files'])} (often used by writing tools)")
        if meta["suspicious_hits"]:
            print(f"  suspicious tokens found: {meta['suspicious_hits']}")
        else:
            print("  No AI-tool fingerprints found in metadata.")
        lines = extract_text_from_docx(path)
    else:
        lines = extract_text_from_plain(path)
        print("(plain text file — no document metadata to check)")

    print("\n== Text style signals ==")
    cliches = find_cliches(lines)
    if cliches:
        print(f"  {len(cliches)} AI-cliche phrase(s) found:")
        for phrase, examples in cliches.items():
            print(f"    - '{phrase}'  (e.g. \"{examples[0]}\")")
    else:
        print("  No stock AI-cliche phrases found.")

    openers = bullet_opener_repetition(lines)
    if openers:
        print(f"  Repeated bullet openers: {openers}")
    else:
        print("  Bullet openers look varied.")

    burst = burstiness_report(lines)
    print(f"  Sentence length variance: {burst}")
    if burst.get("low_variance_flag"):
        print("  Sentence lengths are unusually uniform — a common AI-text tell.")

    print("\n== Harvard FAS resume-guide checks ==")
    print("   (careerservices.fas.harvard.edu/resources/create-a-strong-resume)")
    pronoun_hits = harvard_pronoun_check(lines)
    if pronoun_hits:
        print(f"  Personal pronouns found ({len(pronoun_hits)}) — Harvard: \"Don't use personal pronouns (such as I or We)\":")
        for h in pronoun_hits[:10]:
            print(f"    - \"{h}\"")
    else:
        print("  No personal pronouns (I/We/My/Our) found — matches Harvard's guidance.")

    weak_openers = harvard_weak_opener_check(lines)
    if weak_openers:
        print(f"  {len(weak_openers)} bullet(s) open with a word not on Harvard's action-verb list:")
        for w in weak_openers[:15]:
            print(f"    - {w}")
    else:
        print("  Every bullet opens with a verb from Harvard's action-verb bank.")

    print("\nDone. This is heuristic, not a certified AI-detector result.")


def cmd_clean(args):
    path = Path(args.file)
    out_path = Path(args.output) if args.output else path.with_suffix(".cleaned.docx")

    if path.suffix.lower() != ".docx":
        print("clean mode only handles .docx metadata scrubbing; for .txt/.md just hand-edit the flagged lines.")
        sys.exit(1)

    removed = clean_docx_metadata(path, out_path)
    print(f"Wrote: {out_path}")
    if removed["core_props_cleared"]:
        print(f"  Cleared core props: {removed['core_props_cleared']}")
    if removed["app_props_cleared"]:
        print(f"  Cleared app props: {removed['app_props_cleared']}")
    if removed["custom_xml_removed"]:
        print(f"  Removed customXml parts: {removed['custom_xml_removed']}")
    if not any(removed.values()):
        print("  Nothing to clean — metadata was already blank.")
    print("\nNote: this only clears document metadata. It does not rewrite the")
    print("text itself — run 'inspect' on the output and hand-edit any flagged")
    print("cliches / uniform sentence rhythm to change the actual style signal.")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_inspect = sub.add_parser("inspect", help="Report AI-signal findings")
    p_inspect.add_argument("file")
    p_inspect.set_defaults(func=cmd_inspect)

    p_clean = sub.add_parser("clean", help="Strip docx metadata fingerprints")
    p_clean.add_argument("file")
    p_clean.add_argument("-o", "--output")
    p_clean.set_defaults(func=cmd_clean)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
